name: gubbins
description: Gubbins (Genealogies Unbiased By recomBinations In Nucleotide Sequences) is an algorithm that iteratively identifies 
             loci containing elevated densities of base substitutions while concurrently constructing a phylogeny based on the 
             putative point mutations outside of these regions.
keywords:
  - recombination
tools:
  - gubbins:
      description: Rapid phylogenetic analysis of large samples of recombinant bacterial whole genome sequences using Gubbins.
      homepage: https://sanger-pathogens.github.io/gubbins/
      documentation: https://sanger-pathogens.github.io/gubbins/

input:
  - alignment:
      type: file
      description: fasta alignment file
      pattern: "*.{fasta,fas,fa,aln}"

output:
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - filtered_variant_fasta:
      type: file
      description: Filtered variant alignment in fasta format
      pattern: "*.{fasta}"
  - recombination_predictions_embl:
      type: file
      description: Recombination predictions in embl format
      pattern: "*.{recombination_predictions.embl}"
  - recombination_predictions_gff:
      type: file
      description: Recombination predictions in gff format
      pattern: "*.{gff}"
  - branch_base_reconstruction:
      type: file
      description: Branch base reconstruction
      pattern: "*.{branch_base_reconstruction.embl}"
  - snp_distribution:
      type: file
      description: SNP distribution
      pattern: "*.{vcf}"
  - branch_statistics:
      type: file
      description: Per branch statistics
      pattern: "*.{csv}"
  - filtered_variant_phylip:
      type: file
      description: Filtered variant alignment in phylip format
      pattern: "*.{phylip}"
  - final_tree:
      type: file
      description: Recombination removed RAxML phylogenetic tree
      pattern: "*.{final_tree.tre}"
  - final_tree_labelled:
      type: file
      description: Recombination removed RAxML phylogenetic tree (nodes labelled)
      pattern: "*.{node_labelled.final_tree.tre}"

authors:
  - "@avantonder"
